# Generated by Django 2.1.3 on 2018-12-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='include_type',
            field=models.CharField(choices=[('Display', 'Show in Display only'), ('Export', 'Display and include in Loader XML')], default='Export', help_text='Controls if this is a display only field, or included in the loader.', max_length=64),
        ),
    ]
